import type { Metadata } from "next";
import "./globals.css";
import CustomCursor from "../components/CustomCursor";
import { CursorProvider } from "../components/CursorContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={"font-manrope antialiased"}
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        style={{ '--accent-color': '#a259ff' } as any}
      >
        <CursorProvider>
          <CustomCursor />
          {children}
        </CursorProvider>
      </body>
    </html>
  );
}
