import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=satoshi@400,700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital,wght@0,400;1,400&display=swap" rel="stylesheet" />
      </head>
      <body
        className={"font-manrope antialiased"}
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        style={{ '--accent-color': '#a259ff' } as any}
      >
        {children}
      </body>
    </html>
  );
}
